eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_HOST_ZONE:http://localhost:56031/eureka/}
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: health, metrics, prometheus, info
    prometheus:
        metrics:
            export:
                enabled: true
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
server:
    port: ${PORT:8080}
    servlet:
        context-path: /post-service
spring:
    application:
        name: post-service
    profiles:
        active: staging
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: none
